language: php

php:
  - 7.3
  - 8.0

matrix:
  include:
    - php: 7.3
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - mkdir -p build/logs

script:
  - phpunit --verbose --coverage-text --coverage-clover=coverage.clover
# after_script:
#   - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
